# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Unit Tests

on: push

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    # install newest swift version
    - uses: swift-actions/setup-swift@v2
    
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
