# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Unit Tests

on: push

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    
    # install newest swift version
    - uses: swift-actions/setup-swift@v2

    - name: Build
      run: xcodebuild build -scheme YourSchemeName -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
    
    - name: Run tests
      run: xcodebuild test -scheme YourSchemeName -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
