# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Unit Tests

on: push

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    
    # Install ffmpeg using Homebrew
    - name: Install FFmpeg
      run: brew install ffmpeg
    
    # install newest swift version
    - uses: swift-actions/setup-swift@v2
    
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
